### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by saulex**
Hello, I am interested in this project. saulex@gmai.com

### CODE REVIEW

**Comment by saulex** [comment]
hey do you want to talking about of this game?

**Comment by AirManH** [comment]
If you have any problem, open an issue.

**Comment by saulex** [comment]
I cannot compile in android. can you help me with that?

**Comment by AirManH** [comment]
Sorry, I have only build it on Windows and Linux, Android is not tested yet.
Indeed `proj.android/` is auto generated by cocos2d.

**Comment by saulex** [comment]
I can add this setup and test to this project, Do you have any
suggestion to start this process?

**Comment by AirManH** [comment]
No.

**Pull request closed without merging**
